base_url = "https://soniex2.github.io/ganarchy/"

[repo_list_srcs]
"https://ganarchy.autistic.space/index.toml" = { active=true }
"https://ganarchy.github.io/index.toml" = { active=true }

[projects.385e734a52e13949a7a5c71827f6de920dbfea43]
"https://soniex2.autistic.space/git-repos/ganarchy.git".HEAD = { active=true }
